version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passer
      POSTGRES_DB: gestion_ecole
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Utilisez le port par défaut de PostgreSQL (5432)
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gestion_ecole"]
      interval: 5s
      timeout: 5s
      retries: 5

  flask-app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:passer@db:5432/gestion_ecole
    depends_on:
      db:
        condition: service_healthy  # Attend que la base de données soit prête
    networks:
      - mynetwork
    ports:
      - "5000:5000"  # Expose le port 5000 pour l'application Flask
    volumes:
      - .:/app  # Monte le répertoire actuel dans le conteneur pour le développement


volumes:
  postgres_data:

networks:
  mynetwork: