global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # Node Exporter

  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask-app:8000']  # Application Flask