apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-flask-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-flask-app
    spec:
      containers:
      - name: flask-app
        image: "{{ .Values.flask.image.repository }}:{{ .Values.flask.image.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "{{ .Values.flask.env.DATABASE_URL }}"